# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # Add the rest back in once it builds right in Windwos
        #os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore CoseSignTool/CoseSignTool.Tests/CoseSignUnitTests.csproj
    - name: Build
      run: dotnet build --no-restore CoseSignTool/CoseSignTool.Tests/CoseSignUnitTests.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal CoseSignTool/CoseSignTool.Tests/CoseSignTool.Tests.csproj
